# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-02 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("person_pages", "0002_auto_20150611_1525")]

    operations = [
        migrations.AlterModelOptions(
            name="pagefile", options={"base_manager_name": "objects"}
        ),
        migrations.AlterModelOptions(
            name="pagesection",
            options={"base_manager_name": "objects", "ordering": ["ordering"]},
        ),
        migrations.AlterModelOptions(
            name="personpage",
            options={"base_manager_name": "objects", "ordering": ["person"]},
        ),
    ]
